spring.application.name=sensor-management-service

server.port=8081

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/sensor-platform}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
